name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
  workflow_dispatch:

env:
  PROJECT_NAME: vscode-favicon

jobs:
  test:
    name: Test and Lint
    runs-on: prod-vm

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint
        run: npm run lint

      - name: Run tests with coverage
        run: npm run test:ci

      - name: Check coverage threshold
        run: npm run coverage:check

      - name: Security audit
        run: npm audit --audit-level=high
        continue-on-error: true

  deploy:
    name: Deploy to Production
    runs-on: prod-vm
    needs: test
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'

    steps:
      - name: Pull latest code
        run: |
          cd ~/tools/${{ env.PROJECT_NAME }} || exit 1
          git fetch origin
          git reset --hard origin/main

      - name: Install dependencies
        run: |
          export NVM_DIR="$HOME/.nvm"
          [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"
          cd ~/tools/${{ env.PROJECT_NAME }}
          npm ci

      - name: Run integration smoke tests
        run: |
          export NVM_DIR="$HOME/.nvm"
          [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"
          cd ~/tools/${{ env.PROJECT_NAME }}
          # Run only health-related integration tests that work in production
          npm test -- --testPathPattern="tests/integration/health" --maxWorkers=2 || true

      - name: Reload PM2
        run: |
          export NVM_DIR="$HOME/.nvm"
          [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"
          cd ~/tools/${{ env.PROJECT_NAME }}
          if pm2 list | grep -q "vscode-favicon-vm"; then
            pm2 reload ecosystem.vm.config.js --update-env
          else
            pm2 start ecosystem.vm.config.js
          fi
          pm2 save

      - name: Health check
        run: |
          sleep 5
          curl -f http://localhost:8024/health || echo "Warning: Health check failed"

  security:
    name: Security Checks
    runs-on: prod-vm

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run security tests
        run: npm run test:security

      - name: Audit dependencies
        run: npm audit --audit-level=moderate
        continue-on-error: true
