/**
 * SEC-003: Admin API Key Strength Validation Tests
 * Tests enforcement of minimum key length requirements
 */

const { execSync } = require('child_process');

/**
 * Helper to test configuration with specific environment
 * Returns exit code and output
 */
function testConfig(envVars) {
    const envString = Object.entries(envVars)
        .map(([key, value]) => `${key}="${value}"`)
        .join(' ');

    try {
        const output = execSync(
            `${envString} node -e "require('./lib/config.js');"`,
            { encoding: 'utf-8', stdio: 'pipe' }
        );
        return { success: true, output, exitCode: 0 };
    } catch (error) {
        return { success: false, output: error.stderr || error.stdout, exitCode: error.status };
    }
}

describe('SEC-003: Admin API Key Strength Validation', () => {
    describe('Production Environment - Key Length Enforcement', () => {
        test('should REJECT weak API key (< 32 chars) in production', () => {
            const result = testConfig({
                NODE_ENV: 'production',
                ADMIN_API_KEY: 'short-key-123',  // 13 characters
                ADMIN_IPS: '127.0.0.1'
            });

            expect(result.success).toBe(false);
            expect(result.output).toContain('SECURITY: ADMIN_API_KEY must be at least 32 characters in production');
            expect(result.output).toContain('Current length: 13 characters');
            expect(result.output).toContain('openssl rand -hex 32');
        });

        test('should REJECT 31-character key (boundary case) in production', () => {
            const result = testConfig({
                NODE_ENV: 'production',
                ADMIN_API_KEY: 'a'.repeat(31),  // Exactly 31 characters
                ADMIN_IPS: '127.0.0.1'
            });

            expect(result.success).toBe(false);
            expect(result.output).toContain('SECURITY: ADMIN_API_KEY must be at least 32 characters in production');
            expect(result.output).toContain('Current length: 31 characters');
        });

        test('should ACCEPT 32-character key (minimum valid length) in production', () => {
            const result = testConfig({
                NODE_ENV: 'production',
                ADMIN_API_KEY: 'a'.repeat(32),  // Exactly 32 characters
                ADMIN_IPS: '127.0.0.1'
            });

            expect(result.success).toBe(true);
            expect(result.output).not.toContain('SECURITY: ADMIN_API_KEY must be at least 32 characters');
        });

        test('should ACCEPT strong 64-character key in production', () => {
            const result = testConfig({
                NODE_ENV: 'production',
                ADMIN_API_KEY: 'a'.repeat(64),
                ADMIN_IPS: '127.0.0.1'
            });

            expect(result.success).toBe(true);
            expect(result.output).not.toContain('SECURITY: ADMIN_API_KEY must be at least 32 characters');
        });

        test('should ACCEPT key generated by openssl rand -hex 32 (64 chars)', () => {
            // Simulate key generated by: openssl rand -hex 32
            const opensslKey = 'f4a3b2c1d0e9f8a7b6c5d4e3f2a1b0c9d8e7f6a5b4c3d2e1f0a9b8c7d6e5f4a3';
            expect(opensslKey.length).toBe(64); // 32 bytes in hex = 64 characters

            const result = testConfig({
                NODE_ENV: 'production',
                ADMIN_API_KEY: opensslKey,
                ADMIN_IPS: '127.0.0.1'
            });

            expect(result.success).toBe(true);
        });

        test('should allow production to start without API key (IP-based auth only)', () => {
            const result = testConfig({
                NODE_ENV: 'production',
                ADMIN_IPS: '127.0.0.1'
                // No ADMIN_API_KEY set
            });

            expect(result.success).toBe(true);
            expect(result.output).not.toContain('ADMIN_API_KEY');
        });
    });

    describe('Development Environment - Key Length Warning', () => {
        test('should WARN but ALLOW weak API key in development', () => {
            const result = testConfig({
                NODE_ENV: 'development',
                ADMIN_API_KEY: 'weak-dev-key',  // 12 characters
                ADMIN_IPS: '127.0.0.1'
            });

            expect(result.success).toBe(true);
            // Warning is logged but service starts
            expect(result.output).toContain('ADMIN_API_KEY is shorter than recommended 32 characters');
        });

        test('should WARN about production failure for weak key in development', () => {
            const result = testConfig({
                NODE_ENV: 'development',
                ADMIN_API_KEY: 'short',  // 5 characters
                ADMIN_IPS: '127.0.0.1'
            });

            expect(result.success).toBe(true);
            expect(result.output).toContain('This would fail in production');
            expect(result.output).toContain('openssl rand -hex 32');
        });

        test('should accept strong key in development without warning', () => {
            const result = testConfig({
                NODE_ENV: 'development',
                ADMIN_API_KEY: 'a'.repeat(32),
                ADMIN_IPS: '127.0.0.1'
            });

            expect(result.success).toBe(true);
            expect(result.output).not.toContain('ADMIN_API_KEY is shorter than recommended');
        });
    });

    describe('Test Environment - Key Length Warning', () => {
        test('should WARN but ALLOW weak API key in test environment', () => {
            const result = testConfig({
                NODE_ENV: 'test',
                ADMIN_API_KEY: 'test-key-123',  // 12 characters
                ADMIN_IPS: '127.0.0.1',
                FORCE_CONFIG_INIT: 'true'  // Force init in test mode
            });

            expect(result.success).toBe(true);
        });

        test('should accept strong key in test environment', () => {
            const result = testConfig({
                NODE_ENV: 'test',
                ADMIN_API_KEY: 'a'.repeat(32),
                ADMIN_IPS: '127.0.0.1',
                FORCE_CONFIG_INIT: 'true'
            });

            expect(result.success).toBe(true);
        });
    });

    describe('Edge Cases and Validation', () => {
        test('should treat empty string as no API key (allowed)', () => {
            // Empty string is treated as null/undefined by the config parser
            // This is acceptable - no API key means IP-based auth only
            const result = testConfig({
                NODE_ENV: 'production',
                ADMIN_API_KEY: '',  // Empty string - treated as not set
                ADMIN_IPS: '127.0.0.1'
            });

            // Empty string is treated as null, so it's allowed (IP-only auth)
            expect(result.success).toBe(true);
        });

        test('should REJECT whitespace-only API key', () => {
            const result = testConfig({
                NODE_ENV: 'production',
                ADMIN_API_KEY: '    ',  // Whitespace only
                ADMIN_IPS: '127.0.0.1'
            });

            expect(result.success).toBe(false);
            expect(result.output).toContain('ADMIN_API_KEY must be a non-empty string if provided');
        });

        test('should enforce length on actual content, not including trimmed whitespace', () => {
            // Key with trailing whitespace should still be measured by actual length
            const result = testConfig({
                NODE_ENV: 'production',
                ADMIN_API_KEY: 'short  ',  // 5 actual chars + whitespace
                ADMIN_IPS: '127.0.0.1'
            });

            expect(result.success).toBe(false);
        });

        test('should accept API key with exactly 32 alphanumeric characters', () => {
            const key32 = 'abcdefghijklmnopqrstuvwxyz123456';
            expect(key32.length).toBe(32);

            const result = testConfig({
                NODE_ENV: 'production',
                ADMIN_API_KEY: key32,
                ADMIN_IPS: '127.0.0.1'
            });

            expect(result.success).toBe(true);
        });

        test('should accept API key with alphanumeric characters (32+ chars)', () => {
            // Using simple alphanumeric to avoid shell escaping issues
            const keyWithMixed = 'a1b2c3d4e5f6g7h8i9j0k1l2m3n4o5p6';
            expect(keyWithMixed.length).toBeGreaterThanOrEqual(32);

            const result = testConfig({
                NODE_ENV: 'production',
                ADMIN_API_KEY: keyWithMixed,
                ADMIN_IPS: '127.0.0.1'
            });

            expect(result.success).toBe(true);
        });
    });

    describe('Security Documentation in Error Messages', () => {
        test('should include generation command in production error', () => {
            const result = testConfig({
                NODE_ENV: 'production',
                ADMIN_API_KEY: 'weak',
                ADMIN_IPS: '127.0.0.1'
            });

            expect(result.success).toBe(false);
            expect(result.output).toContain('Generate a strong key with: openssl rand -hex 32');
        });

        test('should include current key length in production error', () => {
            const weakKey = 'test123';
            const result = testConfig({
                NODE_ENV: 'production',
                ADMIN_API_KEY: weakKey,
                ADMIN_IPS: '127.0.0.1'
            });

            expect(result.success).toBe(false);
            expect(result.output).toContain(`Current length: ${weakKey.length} characters`);
        });

        test('should include environment context in development warning', () => {
            const result = testConfig({
                NODE_ENV: 'development',
                ADMIN_API_KEY: 'weak',
                ADMIN_IPS: '127.0.0.1'
            });

            expect(result.success).toBe(true);
            // Warning should indicate development environment
            expect(result.output).toMatch(/development|dev/i);
        });
    });

    describe('Integration with Other Security Controls', () => {
        test('should enforce both IP whitelist AND key strength in production', () => {
            const result = testConfig({
                NODE_ENV: 'production',
                ADMIN_API_KEY: 'weak',
                ADMIN_IPS: 'invalid-ip'
            });

            expect(result.success).toBe(false);
            // Should contain errors for both issues
            expect(result.output).toMatch(/ADMIN_API_KEY|ADMIN_IPS/);
        });

        test('should accept production config with strong key and valid IPs', () => {
            const result = testConfig({
                NODE_ENV: 'production',
                ADMIN_API_KEY: 'a'.repeat(32),
                ADMIN_IPS: '127.0.0.1,::1,192.168.1.1'
            });

            expect(result.success).toBe(true);
        });
    });

    describe('Backward Compatibility', () => {
        test('should maintain backward compatibility for development without breaking existing configs', () => {
            // Old configs with weak keys should still work in dev
            const result = testConfig({
                NODE_ENV: 'development',
                ADMIN_API_KEY: 'dev',  // Very short, but allowed in dev
                ADMIN_IPS: '127.0.0.1'
            });

            expect(result.success).toBe(true);
        });

        test('should not break configs without API key (IP-only auth)', () => {
            const prodResult = testConfig({
                NODE_ENV: 'production',
                ADMIN_IPS: '192.168.1.1'
                // No API key - should work fine
            });

            expect(prodResult.success).toBe(true);

            const devResult = testConfig({
                NODE_ENV: 'development',
                ADMIN_IPS: '127.0.0.1'
            });

            expect(devResult.success).toBe(true);
        });
    });

    describe('Real-World Key Examples', () => {
        test('should accept hex key from openssl rand -hex 32', () => {
            // 64 hex characters = 32 bytes of entropy
            const hexKey = 'a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5f6a1b2';
            const result = testConfig({
                NODE_ENV: 'production',
                ADMIN_API_KEY: hexKey,
                ADMIN_IPS: '127.0.0.1'
            });

            expect(result.success).toBe(true);
        });

        test('should accept UUID as API key (36 chars)', () => {
            const uuidKey = '123e4567-e89b-12d3-a456-426614174000';
            expect(uuidKey.length).toBe(36);

            const result = testConfig({
                NODE_ENV: 'production',
                ADMIN_API_KEY: uuidKey,
                ADMIN_IPS: '127.0.0.1'
            });

            expect(result.success).toBe(true);
        });

        test('should reject common weak patterns', () => {
            const weakKeys = [
                'admin',
                'password',
                'secret',
                'key123',
                'test',
                'dev-api-key',
                'my-secret-key'
            ];

            weakKeys.forEach(key => {
                const result = testConfig({
                    NODE_ENV: 'production',
                    ADMIN_API_KEY: key,
                    ADMIN_IPS: '127.0.0.1'
                });

                expect(result.success).toBe(false);
                expect(result.output).toContain('must be at least 32 characters');
            });
        });
    });
});
